from sqlalchemy import inspect

from app.models.user import User


def test_user_fields_are_set_on_construction() -> None:
    """User model fields are set correctly from constructor arguments."""
    user = User(
        email="daniel@example.com",
        password_hash="hash",
        first_name="Daniel",
        last_name="Dadzie",
    )

    assert user.email == "daniel@example.com"
    assert user.password_hash == "hash"
    assert user.first_name == "Daniel"
    assert user.last_name == "Dadzie"


def test_user_id_is_none_before_db_flush() -> None:
    """UUID primary key is generated by SQLAlchemy on INSERT."""
    user = User(
        email="daniel@example.com",
        password_hash="hash",
        first_name="Daniel",
        last_name="Dadzie",
    )

    assert user.id is None


def test_user_email_column_is_unique() -> None:
    """Email must have a database-level unique constraint."""
    mapper = inspect(User)
    email_col = mapper.columns["email"]

    assert email_col.unique is True
